/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package starmap;

import java.awt.*;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import starmap.DataReaders.ConstellationDataReader;
import starmap.DataReaders.MessierDataReader;
import starmap.DataReaders.PlanetDataReader;
import starmap.DataReaders.StarDataReader;
import starmap.Objects.Constellation;
import starmap.Objects.Messier;
import starmap.Objects.Moon;
import starmap.Objects.Planet;
import starmap.Objects.Star;

/**
 *
 * @author pssew
 */
public class Driver extends javax.swing.JFrame {
    
    ArrayList<Star> starList;
    ArrayList<Constellation> constellationList;
    ArrayList<Planet> planetList;
    ArrayList<Messier> messierList;
    Moon moon;
    
    // <editor-fold defaultstate="collapsed" desc="Constructor"> 

    /**
     * Creates new form Application
     */
    public Driver() {
        initComponents();
        latitudeButtonGroup.add(northRadioButton);
        latitudeButtonGroup.add(southRadioButton);
        longitudeButtonGroup.add(westRadioButton);
        longitudeButtonGroup.add(eastRadioButton);
        
        // SET DEFAULT VALUES
        
        // UAH Tech Hall coordinates
        westRadioButton.setSelected(true);
        longDegreeTextField.setText("86");
        minLongTextField.setText("38");
        secLongTextField.setText("47");
        
        northRadioButton.setSelected(true);
        latDegreeTextField.setText("34");
        minLatTextField.setText("43");
        secLatTextField.setText("8");       
        
        // Set DateTime fields to current DateTime
        LocalDateTime currentDateTime = LocalDateTime.now();
                
        dateTextField.setDate(new Date());
        hourTextField.setText(Integer.toString(currentDateTime.getHour()));
        hourOffsetComboBox.setSelectedItem("-6");
        minuteTextField.setText(Integer.toString(currentDateTime.getMinute()));        
        
        load();
    }

    //</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="UI Generated Code and Event Handlers"> 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        latitudeButtonGroup = new javax.swing.ButtonGroup();
        longitudeButtonGroup = new javax.swing.ButtonGroup();
        generateButton = new javax.swing.JButton();
        coordinatePanel = new javax.swing.JPanel();
        latitudeDegreesLabel = new javax.swing.JLabel();
        latDegreeTextField = new javax.swing.JTextField();
        latitudeMinLabel = new javax.swing.JLabel();
        longDegreeTextField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        minLatTextField = new javax.swing.JTextField();
        dateTextField = new com.toedter.calendar.JDateChooser();
        secLatTextField = new javax.swing.JTextField();
        secLongTextField = new javax.swing.JTextField();
        minLongTextField = new javax.swing.JTextField();
        northRadioButton = new javax.swing.JRadioButton();
        eastRadioButton = new javax.swing.JRadioButton();
        westRadioButton = new javax.swing.JRadioButton();
        southRadioButton = new javax.swing.JRadioButton();
        degreeLabel = new javax.swing.JLabel();
        hourLabel = new javax.swing.JLabel();
        minuteLabel = new javax.swing.JLabel();
        degreeLabel1 = new javax.swing.JLabel();
        hourLabel1 = new javax.swing.JLabel();
        minuteLabel1 = new javax.swing.JLabel();
        enterDataButton = new javax.swing.JButton();
        selectAllButton = new javax.swing.JButton();
        hourTextField = new javax.swing.JTextField();
        minuteTextField = new javax.swing.JTextField();
        hourOffsetComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkBoxPanel = new javax.swing.JPanel();
        starsCheckBox = new javax.swing.JCheckBox();
        planetsCheckBox = new javax.swing.JCheckBox();
        constellationsCheckBox = new javax.swing.JCheckBox();
        messierCheckBox = new javax.swing.JCheckBox();
        unselectCheckBox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StarMapGenerator");

        generateButton.setBackground(java.awt.Color.green);
        generateButton.setText("Generate Image");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        coordinatePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Coordinates"));

        latitudeDegreesLabel.setText("Latitude");

        latDegreeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                latDegreeTextFieldKeyReleased(evt);
            }
        });

        latitudeMinLabel.setText("Longitude");

        longDegreeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                longDegreeTextFieldKeyReleased(evt);
            }
        });

        dateLabel.setText("Date/Time");

        minLatTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                minLatTextFieldKeyReleased(evt);
            }
        });

        dateTextField.setMaxSelectableDate(new java.util.Date(4102466399000L));
        dateTextField.setMinSelectableDate(new java.util.Date(-2208967200000L));

        secLatTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                secLatTextFieldKeyReleased(evt);
            }
        });

        secLongTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                secLongTextFieldKeyReleased(evt);
            }
        });

        minLongTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                minLongTextFieldKeyReleased(evt);
            }
        });

        northRadioButton.setText("N");

        eastRadioButton.setText("E");

        westRadioButton.setText("W");

        southRadioButton.setText("S");

        degreeLabel.setText("°");

        hourLabel.setText("'");

        minuteLabel.setText("\"");

        degreeLabel1.setText("°");

        hourLabel1.setText("'");

        minuteLabel1.setText("\"");

        enterDataButton.setText("Enter Data");
        enterDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterDataButtonActionPerformed(evt);
            }
        });

        selectAllButton.setText("Select All");
        selectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });

        hourTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hourTextFieldKeyReleased(evt);
            }
        });

        minuteTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                minuteTextFieldKeyReleased(evt);
            }
        });

        hourOffsetComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-12", "-11", "-10", "-9", "-8", "-7", "-6", "-5", "-4", "-3", "-2", "-1", "0", "+1", "+2", "+3", "+4", "+5", "+6", "+7", "+8", "+9", "+10", "+11", "+12" }));

        jLabel1.setText("hr");

        jLabel2.setText("min");

        javax.swing.GroupLayout coordinatePanelLayout = new javax.swing.GroupLayout(coordinatePanel);
        coordinatePanel.setLayout(coordinatePanelLayout);
        coordinatePanelLayout.setHorizontalGroup(
            coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coordinatePanelLayout.createSequentialGroup()
                .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(coordinatePanelLayout.createSequentialGroup()
                        .addComponent(enterDataButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectAllButton))
                    .addGroup(coordinatePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(coordinatePanelLayout.createSequentialGroup()
                                .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(coordinatePanelLayout.createSequentialGroup()
                                        .addComponent(latitudeMinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(westRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eastRadioButton))
                                    .addGroup(coordinatePanelLayout.createSequentialGroup()
                                        .addComponent(latitudeDegreesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(northRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(southRadioButton)))
                                .addGap(20, 20, 20)
                                .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(latDegreeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(longDegreeTextField)))
                            .addGroup(coordinatePanelLayout.createSequentialGroup()
                                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(degreeLabel1)
                            .addComponent(degreeLabel))))
                .addGap(13, 13, 13)
                .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minLongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minLatTextField)
                    .addComponent(hourTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hourLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 9, Short.MAX_VALUE)
                        .addComponent(hourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(coordinatePanelLayout.createSequentialGroup()
                            .addComponent(secLatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(minuteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coordinatePanelLayout.createSequentialGroup()
                            .addComponent(secLongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(minuteLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(coordinatePanelLayout.createSequentialGroup()
                        .addComponent(minuteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(hourOffsetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        coordinatePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {enterDataButton, selectAllButton});

        coordinatePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {latitudeDegreesLabel, latitudeMinLabel});

        coordinatePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {latDegreeTextField, longDegreeTextField, minLatTextField, minLongTextField, secLatTextField, secLongTextField});

        coordinatePanelLayout.setVerticalGroup(
            coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coordinatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(coordinatePanelLayout.createSequentialGroup()
                        .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(latitudeDegreesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(northRadioButton)
                            .addComponent(southRadioButton)
                            .addComponent(latDegreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(degreeLabel)
                            .addComponent(minLatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hourLabel)
                            .addComponent(secLatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minuteLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(westRadioButton)
                            .addComponent(latitudeMinLabel)
                            .addComponent(longDegreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(degreeLabel1)
                            .addComponent(minLongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hourLabel1)
                            .addComponent(secLongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minuteLabel1)
                            .addComponent(eastRadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(minuteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(coordinatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterDataButton)
                    .addComponent(selectAllButton)
                    .addComponent(hourOffsetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        coordinatePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {latDegreeTextField, longDegreeTextField, minLatTextField, minLongTextField, secLatTextField, secLongTextField});

        coordinatePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {latitudeDegreesLabel, latitudeMinLabel});

        checkBoxPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Image Selection"));

        starsCheckBox.setText("Stars");
        starsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starsCheckBoxActionPerformed(evt);
            }
        });

        planetsCheckBox.setText("Major Planets");
        planetsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planetsCheckBoxActionPerformed(evt);
            }
        });

        constellationsCheckBox.setText("Major Constellations");
        constellationsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constellationsCheckBoxActionPerformed(evt);
            }
        });

        messierCheckBox.setText("Messier Objects");
        messierCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messierCheckBoxActionPerformed(evt);
            }
        });

        unselectCheckBox.setText("Unselect All");
        unselectCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unselectCheckBoxActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane2.setViewportView(textArea);

        javax.swing.GroupLayout checkBoxPanelLayout = new javax.swing.GroupLayout(checkBoxPanel);
        checkBoxPanel.setLayout(checkBoxPanelLayout);
        checkBoxPanelLayout.setHorizontalGroup(
            checkBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkBoxPanelLayout.createSequentialGroup()
                .addGroup(checkBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkBoxPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(checkBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unselectCheckBox)
                            .addComponent(starsCheckBox)
                            .addComponent(constellationsCheckBox)
                            .addComponent(messierCheckBox)
                            .addComponent(planetsCheckBox)))
                    .addGroup(checkBoxPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        checkBoxPanelLayout.setVerticalGroup(
            checkBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkBoxPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(starsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planetsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(constellationsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messierCheckBox)
                .addGap(6, 6, 6)
                .addComponent(unselectCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("Save Image");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(coordinatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(checkBoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(generateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coordinatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(generateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1))
                        .addComponent(checkBoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        try 
        {
            Calendar selectedDate = dateTextField.getCalendar();
            int hour = Integer.parseInt(hourTextField.getText());
            int hourOffset = Integer.parseInt(hourOffsetComboBox.getSelectedItem().toString());
            
            int localHour = hour - hourOffset;
            
            if (localHour < 0)
            {
                localHour += 24;
            }
            
            if (localHour > 23)
            {
                localHour -= 24;
            }        
            
            int minute = Integer.parseInt(minuteTextField.getText());   
            
            
            LocalDateTime dateTime = LocalDateTime.of(
                    selectedDate.get(Calendar.YEAR), 
                    selectedDate.get(Calendar.MONTH) + 1, 
                    selectedDate.get(Calendar.DAY_OF_MONTH), 
                    localHour, 
                    minute);
            
            double julianDate = Calculation.getJulianDate(dateTime);      
            System.out.println("Julian Date: " + julianDate);
            
            int latitudeDegrees = Integer.parseInt(latDegreeTextField.getText());
            int latitudeMinutes = Integer.parseInt(minLatTextField.getText());
            int latitudeSeconds = Integer.parseInt(secLatTextField.getText());
            String latitudeDirection = "";
            
            if (northRadioButton.isSelected())
            {
                latitudeDirection = "North";
            }
            else if (southRadioButton.isSelected())
            {
                latitudeDirection = "South";
            } 
            
            int longitudeDegrees = Integer.parseInt(longDegreeTextField.getText());
            int longitudeMinutes = Integer.parseInt(minLongTextField.getText());
            int longitudeSeconds = Integer.parseInt(secLongTextField.getText());
            String longitudeDirection = "";
            
            if (westRadioButton.isSelected())
            {
                longitudeDirection = "West";
            }
            else if (eastRadioButton.isSelected())
            {
                longitudeDirection = "East";
            }                    
                     
            LocalTime greenwichSiderealTime = Calculation.getGreenwichSiderealTime(dateTime);            
            
            // Coordinates for UAH are 34° 43' 8.0904'' N, 86° 38' 47.3532'' W   
            double latitude = Calculation.getDecimalCoordinate(latitudeDegrees, latitudeMinutes, latitudeSeconds, latitudeDirection);
            double longitude = Calculation.getDecimalCoordinate(longitudeDegrees, longitudeMinutes, longitudeSeconds, longitudeDirection);
            textArea.append("Latitude = " + latitude + "\n");
            textArea.append("Longitude = " + longitude + "\n");
            
            // Calculate azimuth and elevation coordinates from the specified time and location
            for (Star star : starList)
            {
                star.calculateHorizonCoordinates(latitude, longitude, greenwichSiderealTime);
            }
            
            for (Constellation constellation : constellationList)
            {
                constellation.calculateHorizonCoordinates(latitude, longitude, greenwichSiderealTime);
            }
            
            for (Planet planet : planetList)
            {
                planet.getIntermediateValues(julianDate);
                planet.calculateHorizonCoordinates(latitude, longitude, greenwichSiderealTime);
            }
            
            for (Messier messier : messierList)
            {
                messier.calculateHorizonCoordinates(latitude, longitude, greenwichSiderealTime);
            }
            
//            moon.getIntermediateValues(julianDate);
//            moon.calculateHorizonCoordinates(latitude, longitude, greenwichSiderealTime);
                        
            // Output positions of objects
//            for (Star star : starList)
//            {
//                if (star.name.trim().isEmpty())
//                {
//                    System.out.println("Current Azimuth/Elevation of **NO NAME**: "
//                      + star.azimuth + "°, " +star.elevation + "°");
//                }
//                else
//                {
//                    System.out.println("Current Azimuth/Elevation of " + star.name + ": "
//                      + star.azimuth + "°, " +star.elevation + "°");
//                }
//            }
  
//            for (Constellation constellation : constellationList)
//            {
//                System.out.println("Current Azimuth/Elevation of " + constellation.name + ": "
//                  + constellation.azimuth + "°, " +constellation.elevation + "°");
//            }

            for (Planet planet : planetList)
            {
                System.out.println("Current Azimuth/Elevation of " + planet.name + ": "
                    + planet.azimuth + "°, " + planet.elevation + "°");
            }
            
//            for (Messier messier : messierList)
//            {
//                System.out.println("Current Azimuth/Elevation of " + messier.name + ": "
//                  + messier.azimuth + "°, " + messier.elevation + "°");
//            }

//            System.out.println("Current Azimuth/Elevation of " + moon.name + ": "
//                + moon.azimuth + "°, " + moon.elevation + "°");





//            // Polaris
//            String objectName = "Polaris";
//            double rightAscention = 2.133333333;
//            double declination = 89.26413805;
//            
//            Map<String, Double> map = Calculation.getAzimuthAndElevation(rightAscention, declination, latitude, longitude, greenwichSiderealTime);
//            
//            textArea.append("Current Azimuth/Elevation of " + objectName 
//                    + " from " + latitudeDegrees + "° " + latitudeMinutes + "' "
//                    + latitudeSeconds + "'' " + latitudeDirection + " " 
//                    + longitudeDegrees + "° " + longitudeMinutes + "' "
//                    + longitudeSeconds + "'' " + longitudeDirection + ": "
//                    + map.get("Azimuth") + "°, " + map.get("Elevation") + "°\n");
//            
//            
//            // Alpheratz
//            objectName = "Alpheratz";
//            rightAscention = 0.13976888;
//            declination = 29.09082805;
//            
//            map = Calculation.getAzimuthAndElevation(rightAscention, declination, latitude, longitude, greenwichSiderealTime);
//            
//            textArea.append("Current Azimuth/Elevation of " + objectName 
//                    + " from " + latitudeDegrees + "° " + latitudeMinutes + "' "
//                    + latitudeSeconds + "'' " + latitudeDirection + " " 
//                    + longitudeDegrees + "° " + longitudeMinutes + "' "
//                    + longitudeSeconds + "'' " + longitudeDirection + ": "
//                    + map.get("Azimuth") + "°, " + map.get("Elevation") + "°\n");
//            
//            // Markab
//            objectName = "Markab";
//            rightAscention = 23.07933801;
//            declination = 15.20536786;
//            
//            map = Calculation.getAzimuthAndElevation(rightAscention, declination, latitude, longitude, greenwichSiderealTime);
//            
//            textArea.append("Current Azimuth/Elevation of " + objectName 
//                    + " from " + latitudeDegrees + "° " + latitudeMinutes + "' "
//                    + latitudeSeconds + "'' " + latitudeDirection + " " 
//                    + longitudeDegrees + "° " + longitudeMinutes + "' "
//                    + longitudeSeconds + "'' " + longitudeDirection + ": "
//                    + map.get("Azimuth") + "°, " + map.get("Elevation") + "°\n");   

            MapPanel mapPanel = new MapPanel(starList);
            JScrollPane mapPanelScrollPane = new JScrollPane(mapPanel);
            
            JPanel mapFramePanel = new JPanel();            
            mapFramePanel.setLayout(new BorderLayout());
            mapFramePanel.add(mapPanelScrollPane);
            
            JFrame mapFrame = new JFrame("Sky Map");
            mapFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            mapFrame.add(mapFramePanel);
            mapFrame.setSize(1000, 1000);
            mapFrame.setVisible(true);
            
            try
            {
                BufferedImage image = new BufferedImage(mapPanel.getWidth(), mapPanel.getHeight(), BufferedImage.TYPE_INT_RGB);
                
                // changes the pixel size of image // needs the first BufferedImage to be called OGimage
                //Image tmp = OGimage.getScaledInstance(2550, 2550, Image.SCALE_DEFAULT);
                //BufferedImage image = new BufferedImage(2550, 2550, BufferedImage.TYPE_INT_ARGB);
                
                Graphics2D graphics2D = image.createGraphics();
                mapPanel.paint(graphics2D);
                //ImageIO.write(image,"jpeg", new File("jmemPractice.jpeg"));
                
                
                
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setCurrentDirectory(new java.io.File("."));
                fileChooser.setDialogTitle("File Dialog");
                fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
                
                if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) { 
                    System.out.println("\n\ngetCurrentDirectory(): " 
                        +  fileChooser.getCurrentDirectory());
                    System.out.println("getSelectedFile() : " 
                        +  fileChooser.getSelectedFile());
                    
                    File saveImage = new File(fileChooser.getSelectedFile() + ".jpeg");
                    ImageIO.write(image, "jpeg", saveImage);
                    System.out.println("File written Successfully");
                }
                else {
                    System.out.println("No Selection ");
                }
  
            }
            catch(Exception exception)
            {
                //code
            }
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(Driver.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_generateButtonActionPerformed
    /*
    * METHOD: starsCheckBoxActionPerformed()
    *
    * DESCRIPTION: this method prints a message when the stars check box has
    *               been selected.
    */
    private void starsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starsCheckBoxActionPerformed
        String stars = "";
        if(starsCheckBox.isSelected())
        {
            stars = stars + " " + starsCheckBox.getText() + '\n';
            textArea.setText(stars);
        }
        else
            textArea.setText("");
    }//GEN-LAST:event_starsCheckBoxActionPerformed
    /*
    * METHOD: planetsCheckBoxActionPerformed
    *
    * DESCRIPTION: this method prints a message when the planets check box has
    *               been selected.
    */
    private void planetsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planetsCheckBoxActionPerformed
        String planets = "";
        if(planetsCheckBox.isSelected())
        {
            planets = planets + " " + planetsCheckBox.getText() + '\n';
            textArea.setText(planets);
        }
        else
            textArea.setText("");
    }//GEN-LAST:event_planetsCheckBoxActionPerformed
    /*
    * METHOD: constellationsCheckBoxActionPerformed
    *
    * DESCRIPTION: this method prints a message when the constellations check 
    *               box has been selected.
    */
    private void constellationsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constellationsCheckBoxActionPerformed
        String constellations = "";
        if(constellationsCheckBox.isSelected())
        {
            constellations = constellations + " " + constellationsCheckBox.getText() + '\n';
            textArea.setText(constellations);
        }
        else
            textArea.setText("");
    }//GEN-LAST:event_constellationsCheckBoxActionPerformed
    /*
    * METHOD: messierCheckBoxActionPerformed
    *
    * DESCRIPTION: this method prints a message when the Messier check box has
    *               been selected.
    */
    private void messierCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messierCheckBoxActionPerformed
        String messier = "";
        if(messierCheckBox.isSelected())
        {
            messier = messier + " " + messierCheckBox.getText() + '\n';
            textArea.setText(messier);
        }
        else
            textArea.setText("");
    }//GEN-LAST:event_messierCheckBoxActionPerformed
    /*
    * METHOD: unselectCheckBoxActionPerformed
    *
    * DESCRIPTION: this method prints a message when the unselect check box has
    *               been selected.
    */
    private void unselectCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unselectCheckBoxActionPerformed
        String unselect = "";
        if(unselectCheckBox.isSelected())
        {
            unselect = unselect + " " + unselectCheckBox.getText() + '\n';
            textArea.setText(unselect);
        }
        else
            textArea.setText("");
    }//GEN-LAST:event_unselectCheckBoxActionPerformed
    /*
    * METHOD: unselectCheckBoxActionPerformed
    *
    * DESCRIPTION: this method prints a message when the unselect check box has
    *               been selected.
    */
    private void selectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButtonActionPerformed
        String s1 = "";
        
        if(starsCheckBox.isSelected())
        {
            //starsCheckBox.setSelected(true);
            s1 = s1 + " " + starsCheckBox.getText() + '\n';  
        }
//        else
//        {
//            starsCheckBox.setSelected(false);
//            s1 = s1 + "not selected";
//        }
        
        if(planetsCheckBox.isSelected())
        {
            planetsCheckBox.setSelected(true);
            s1 = s1 + " " + planetsCheckBox.getText() + '\n';
        }
        else
            planetsCheckBox.setSelected(false);
        
        if(constellationsCheckBox.isSelected())
        {
            s1 = s1 + " " + constellationsCheckBox.getText() + '\n';
        }
        
        if(messierCheckBox.isSelected())
        {
            s1 = s1 + " " + messierCheckBox.getText() + '\n';
        }
        
        if(unselectCheckBox.isSelected())
        {
            s1 = s1 + " " + unselectCheckBox.getText() + '\n';
        }
        
        textArea.setText(s1);
    }//GEN-LAST:event_selectAllButtonActionPerformed

    private void enterDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterDataButtonActionPerformed
        // Get latitiude in degrees and print to textArea.
        //String infoMsg = "Please enter a Latitude value between " + "[-90, +90]";
        float latDegree = Float.parseFloat(latDegreeTextField.getText());
        textArea.append(latDegree + " degrees\n");
        

        double latMinute = Double.parseDouble(longDegreeTextField.getText());
        textArea.append(latMinute + " minutes\n");


//        
//        float lonDegree = Float.parseFloat(lonDegTextField.getText());
//        textArea.append(lonDegree + " degrees\n");
//        
//        double lonMinute = Double.parseDouble(lonMinTextField.getText());
//        textArea.append(lonMinute + " minutes\n");
        
//        if((latDegree < -90) || (latDegree > 90))
//            JOptionPane.showMessageDialog(null, infoMsg);
//        else
//            textArea.append(latDegree + " degrees\n");
        
        //Get latitude in minutes and print to textArea.
        //double latMinute = Double.parseDouble(latMinTextField.getText());
        //textArea.append(latMinute + " minutes\n");
        
        //Get longitude in degrees and print to textArea.
        //String infoMsg2 = "Please enter a Longitude value between " + "[-180, +180]";
        //float lonDegree = Float.parseFloat(lonDegTextField.getText());
        //textArea.append(lonDegree + " degrees\n");
        
//        if((lonDegree < -180) || (lonDegree > 180))
//            JOptionPane.showMessageDialog(null, infoMsg2);
//        else
//            textArea.append(lonDegree + " degrees\n");
        
        //Get longitude in minutes and print to textArea
        //double lonMinute = Double.parseDouble(lonMinTextField.getText());
        //textArea.append(lonMinute + " minutes\n");
        
        
//        dateChooser.getDate();
//        textArea.setText(dateChooser);
        
    }//GEN-LAST:event_enterDataButtonActionPerformed

    private void latDegreeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_latDegreeTextFieldKeyReleased
        // Gets the Longitude Degree value from user:
        int latDegree = Integer.parseInt(latDegreeTextField.getText());
        
        if((latDegree < 0) || (latDegree > 90))
        {
            latDegreeTextField.setBackground(Color.YELLOW);
        }
        else
        {
            latDegreeTextField.setBackground(Color.WHITE);
            textArea.append(latDegree + "°\n");
        }
    }//GEN-LAST:event_latDegreeTextFieldKeyReleased

    private void minLatTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minLatTextFieldKeyReleased
        // Gets the Latitude Hours value from user:
        int latHours = Integer.parseInt(minLatTextField.getText());
        
        if((latHours < 0) || (latHours > 59))
        {
            minLatTextField.setBackground(Color.YELLOW);
        }          
        else
        {
            minLatTextField.setBackground(Color.WHITE);
            textArea.append(latHours + "'\n");
        }
    }//GEN-LAST:event_minLatTextFieldKeyReleased

    private void secLatTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secLatTextFieldKeyReleased
        int latMinutes = Integer.parseInt(secLatTextField.getText());
        
        if((latMinutes < 0) || (latMinutes > 59))
        {
            secLatTextField.setBackground(Color.YELLOW);
        }          
        else
        {
            secLatTextField.setBackground(Color.WHITE);
            textArea.append(latMinutes + "\"\n");
        }
    }//GEN-LAST:event_secLatTextFieldKeyReleased

    private void longDegreeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_longDegreeTextFieldKeyReleased
        // Gets the Longitude Degree value from user:
        int longDegree = Integer.parseInt(longDegreeTextField.getText());
        
        if((longDegree < 0) || (longDegree > 180))
        {
            longDegreeTextField.setBackground(Color.YELLOW);
        }
        else
        {
            longDegreeTextField.setBackground(Color.WHITE);
            textArea.append(longDegree + "°\n");
        }
    }//GEN-LAST:event_longDegreeTextFieldKeyReleased

    private void minLongTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minLongTextFieldKeyReleased
        int longMinutes = Integer.parseInt(minLongTextField.getText());
        
        if((longMinutes < 0) || (longMinutes > 59))
        {
            minLongTextField.setBackground(Color.YELLOW);
        }          
        else
        {
            minLongTextField.setBackground(Color.WHITE);
            textArea.append(longMinutes + "\"\n");
        }
    }//GEN-LAST:event_minLongTextFieldKeyReleased

    private void secLongTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secLongTextFieldKeyReleased
        int latMinutes = Integer.parseInt(secLongTextField.getText());
        
        if((latMinutes < 0) || (latMinutes > 59))
        {
            secLongTextField.setBackground(Color.YELLOW);
        }          
        else
        {
            secLongTextField.setBackground(Color.WHITE);
            textArea.append(latMinutes + "\"\n");
        }
    }//GEN-LAST:event_secLongTextFieldKeyReleased

    private void hourTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hourTextFieldKeyReleased
        int hour = Integer.parseInt(hourTextField.getText());
        
        if((hour < 0) || (hour > 23))
        {
            hourTextField.setBackground(Color.YELLOW);
        }          
        else
        {
            hourTextField.setBackground(Color.WHITE);
            textArea.append(hour + "\"\n");
        }
    }//GEN-LAST:event_hourTextFieldKeyReleased

    private void minuteTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minuteTextFieldKeyReleased
        int minute = Integer.parseInt(minuteTextField.getText());
        
        if((minute < 0) || (minute > 59))
        {
            minuteTextField.setBackground(Color.YELLOW);
        }          
        else
        {
            minuteTextField.setBackground(Color.WHITE);
            textArea.append(minute + "\"\n");
        }
    }//GEN-LAST:event_minuteTextFieldKeyReleased
    
    // </editor-fold>
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Driver().setVisible(true);
            }
        });
    }
    
    private void load()
    {        
        Runnable r = new Runnable() 
        {
            public void run() 
            {
                readData();
            }
        };
        
        ExecutorService executor = Executors.newCachedThreadPool();
        executor.submit(r);
    }
    
    private void readData()
    {
        System.out.println("Reading data from file");
        
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        StarDataReader starDataReader = new StarDataReader();
        
        starList = starDataReader.readData();
        
        ConstellationDataReader constellationDataReader = new ConstellationDataReader();
        
        constellationList = constellationDataReader.readData();
        
        PlanetDataReader planetDataReader = new PlanetDataReader();
        
        planetList = planetDataReader.readData();
        
        MessierDataReader messierDataReader = new MessierDataReader();
        
        messierList = messierDataReader.readData();
        
        moon = new Moon();
        
        this.setCursor(Cursor.getDefaultCursor());
        
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Members">

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel checkBoxPanel;
    private javax.swing.JCheckBox constellationsCheckBox;
    private javax.swing.JPanel coordinatePanel;
    private javax.swing.JLabel dateLabel;
    private com.toedter.calendar.JDateChooser dateTextField;
    private javax.swing.JLabel degreeLabel;
    private javax.swing.JLabel degreeLabel1;
    private javax.swing.JRadioButton eastRadioButton;
    private javax.swing.JButton enterDataButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JLabel hourLabel1;
    private javax.swing.JComboBox<String> hourOffsetComboBox;
    private javax.swing.JTextField hourTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField latDegreeTextField;
    private javax.swing.ButtonGroup latitudeButtonGroup;
    private javax.swing.JLabel latitudeDegreesLabel;
    private javax.swing.JLabel latitudeMinLabel;
    private javax.swing.JTextField longDegreeTextField;
    private javax.swing.ButtonGroup longitudeButtonGroup;
    private javax.swing.JCheckBox messierCheckBox;
    private javax.swing.JTextField minLatTextField;
    private javax.swing.JTextField minLongTextField;
    private javax.swing.JLabel minuteLabel;
    private javax.swing.JLabel minuteLabel1;
    private javax.swing.JTextField minuteTextField;
    private javax.swing.JRadioButton northRadioButton;
    private javax.swing.JCheckBox planetsCheckBox;
    private javax.swing.JTextField secLatTextField;
    private javax.swing.JTextField secLongTextField;
    private javax.swing.JButton selectAllButton;
    private javax.swing.JRadioButton southRadioButton;
    private javax.swing.JCheckBox starsCheckBox;
    private javax.swing.JTextArea textArea;
    private javax.swing.JCheckBox unselectCheckBox;
    private javax.swing.JRadioButton westRadioButton;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>

}
